# Generated by Django 6.0.5 on 2026-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Режиссёр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_showing', models.BooleanField(default=True, verbose_name='Сейчас в прокате')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
